
-- شغّلي هذا الملف مرة واحدة في Supabase > SQL Editor
create extension if not exists pgcrypto;

create table if not exists public.report_types (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name_ar text not null,
  category_ar text not null,
  active boolean not null default true
);

create table if not exists public.report_counters (
  report_year integer not null,
  type_code text not null,
  counter integer not null default 0,
  primary key (report_year, type_code)
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  report_number text unique,
  type_code text not null,
  template_name text not null,
  category text not null,
  title text not null,
  report_date date not null,
  department text,
  beneficiaries_count integer not null default 0 check (beneficiaries_count >= 0),
  payload jsonb not null default '{}'::jsonb,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.report_attachments (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.reports(id) on delete cascade,
  file_name text not null,
  storage_path text not null,
  mime_type text,
  size_bytes bigint,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  anonymous_visitor_id text not null,
  session_id text not null,
  event_type text not null check (event_type in ('page_view','report_view','report_created','report_print','report_download','report_share')),
  report_id uuid references public.reports(id) on delete set null,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create or replace function public.next_report_number(p_code text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  y integer := extract(year from now())::integer;
  n integer;
begin
  insert into public.report_counters(report_year,type_code,counter)
  values (y,p_code,1)
  on conflict (report_year,type_code)
  do update set counter = public.report_counters.counter + 1
  returning counter into n;
  return 'SCH-' || y || '-' || upper(p_code) || '-' || lpad(n::text,4,'0');
end $$;

create or replace function public.set_report_number()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.report_number is null or new.report_number = '' then
    new.report_number := public.next_report_number(new.type_code);
  end if;
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists trg_set_report_number on public.reports;
create trigger trg_set_report_number
before insert or update on public.reports
for each row execute function public.set_report_number();

alter table public.report_types enable row level security;
alter table public.reports enable row level security;
alter table public.report_attachments enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "types_read" on public.report_types;
create policy "types_read" on public.report_types for select to authenticated using (true);

drop policy if exists "reports_read" on public.reports;
create policy "reports_read" on public.reports for select to authenticated using (true);

drop policy if exists "reports_insert" on public.reports;
create policy "reports_insert" on public.reports for insert to authenticated with check (auth.uid() = created_by);

drop policy if exists "reports_update_own" on public.reports;
create policy "reports_update_own" on public.reports for update to authenticated using (auth.uid() = created_by) with check (auth.uid() = created_by);

drop policy if exists "reports_delete_own" on public.reports;
create policy "reports_delete_own" on public.reports for delete to authenticated using (auth.uid() = created_by);

drop policy if exists "attachments_read" on public.report_attachments;
create policy "attachments_read" on public.report_attachments for select to authenticated using (true);

drop policy if exists "attachments_insert" on public.report_attachments;
create policy "attachments_insert" on public.report_attachments for insert to authenticated with check (auth.uid() = created_by);

drop policy if exists "analytics_insert" on public.analytics_events;
create policy "analytics_insert" on public.analytics_events for insert to authenticated with check (auth.uid() = created_by);

insert into storage.buckets (id,name,public)
values ('report-evidence','report-evidence',false)
on conflict (id) do update set public=false;

drop policy if exists "report_files_read" on storage.objects;
create policy "report_files_read" on storage.objects for select to authenticated using (bucket_id='report-evidence');

drop policy if exists "report_files_insert" on storage.objects;
create policy "report_files_insert" on storage.objects for insert to authenticated with check (bucket_id='report-evidence');
